### ISSUE TITLE
Check that autovectorization works with the clamp

### ISSUE THREAD

**Issue by LTLA** [LTLA/umappp#11]
Not sure if I should replace `min` and `max` with ternary operators.

More generally, consider turning the number of dimensions into a compile-time constant (with `-1` as a fallback for a dynamic number of dimensions, like how Eigen does it). This might allow the compiler to achieve further optimizations. ¯\\\_(ツ)\_/¯

**Comment by jlmelville** [comment]
FWIW seems like at some point I made `clamp` in `uwot` use ternary operators:

```C++
inline auto clamp(float v, float lo, float hi) -> float {
  float t = v < lo ? lo : v;
  return t > hi ? hi : t;
}
```

I do remember finding some unpredictable effects of `inline` (sometimes it had a noticeable and consistent effect, sometimes it didn't), perhaps I also found an effect with using std::max/min vs ternary operator. I never did any proper profiling, I wouldn't be surprised if the effect was entirely compiler-specific.

**Comment by LTLA** [comment]
Trying with the following code:

```cpp
#include <cstdlib>
#include <iostream>
#include <vector>
#include <algorithm>

double clamp1(double val) {
    return std::min(4.0, std::max(val, -4.0));
}

double clamp2(double val) {
    return (val > 4.0 ? 4.0 : (val < -4.0 ? -4.0 : val));
}

int main(int argc, char* argv[]) {
    int dims = std::atoi(argv[1]);
//    constexpr int dims = 5;

    std::vector<double> left(dims);
    std::vector<double> right(dims);
    for (int i = 0; i < dims; ++i) {
        left[i] = i;
        right[i] = dims - i;
    }

    std::vector<double> out(dims);
    for (int i = 0; i < dims; ++i) {
        double val = clamp2(left[i] - right[i]);
        out[i] = val * val;
    }

    // Make sure the compiler doesn't optimize it all away.
    double summation = 0;
    for (int i = 0; i < dims; ++i) {
        summation += out[i];
    }
    std::cout << summation << std::endl;
    return 0;
}
```

and compiling on clang with `g++ -std=c++17 -O2 -Rpass=loop-vectorize blah.cpp` (`g++` is just an alias) gives me:

```
blah.cpp:26:5: remark: vectorized loop (vectorization width: 2, interleaved count: 2) [-Rpass=loop-vectorize]
    for (int i = 0; i < dims; ++i) {
    ^
```

Regardless of whether I use `clamp1` or `clamp2`, so I guess both are fine. Will try on GCC when I get home.

Interestingly, if we switch to the `constexpr int dims`, the compiler will not do any vectorization until `dims` gets large enough (28 or higher, on my system). Inspection of the assembly indicates that the loop is just unrolled. I guess that the compiler considers this to be even faster than SIMD instructions, don't know enough to know whether that's reasonable.

**Comment by LTLA** [comment]
GCC 7.5.0, on the other hand, refuses to vectorize the loop, with:

```
blah.cpp:31:23: note: not vectorized: control flow in loop.
blah.cpp:31:23: note: bad loop form.
```

when I run `g++ blah.cpp -std=c++17 -O3 -ftree-vectorizer-verbose=2 -fopt-info-loop-missed`.

This is regardless of whether `clamp1` or `clamp2` is used. Seems like a missed optimization opportunity on GCC's part, but either way, it seems it doesn't matter whether I use `?` or `min`/`max`. So I'll stick with the latter as it's easier on the eye.

Also, to finish up the other thought: I tried implementing UMAP with a compile-time constant number of dimensions, but it didn't give any appreciable speed-up. In fact, on both Clang and GCC, it actually showed a consistent perf degradation (2-5%) on the MNIST digits example. A bit shocking that the compiler generates worse code with _more_ information.
