### ISSUE TITLE
plotting on an xy plot

### ISSUE THREAD

**Issue by lketdegh** [LTLA/umappp#15]
Hi @LTLA ,
I don't understand much about how to use it.
UMAP is work for reduct dimemsion but how do I draw the in xy plot via result?

**Comment by LTLA** [comment]
Is there a reason you're using a C++ library? If you just want to create and plot UMAPs, I'd suggest you start with either the original Python package or the [**uwot** R package](https://github.com/jlmelville), which operate in frameworks that have more plotting functionality. If you must use C++, I suppose **gnuplot** could work.

**Comment by lketdegh** [comment]
Or in other words, I got a graph with multiple clusters via the Python package and I hope I can reproduce it using C++.

**Comment by lketdegh** [comment]
Hello @LTLA ,
Thank you for help about solve the problem above. The plot made with several cluster already like I want. Is there any way to know each cluster belongs to what data is it like as the photo below from Python package ? 
![image](https://user-images.githubusercontent.com/11409456/226867257-c5e712c6-3110-4781-8469-cd318474e707.png)

**Comment by lketdegh** [comment]
@jlmelville @LTLA 
Really appreciate your help in resolving the problem and it's useful for me.
