### ISSUE TITLE
Ruby bindings

### ISSUE THREAD

**Issue by kojix2** [LTLA/umappp#5]
Hi! @LTLA 

I created a Ruby wrapper for Umappp.
It doesn't work exactly the same as yaumap, so I may have made a mistake somewhere, but basically it appears to be working well.

https://github.com/kojix2/umap

Have a nice day!

**Comment by LTLA** [comment]
This is very neat. My Ruby knowledge is pretty basic but it looks cool.

I wouldn't worry about the differences, I don't get exactly the same results as **uwot** either. Probably something to do with numerical imprecision, compiler settings, etc. Doesn't really matter in the big picture.
